spring:
  application:
    name: the-employee-handbook
  datasource:
    url: jdbc:postgresql://localhost:5435/vibe_db
    username: my-user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        model: llama3

      embedding:
        model: nomic-embed-text

    vectorstore:
      pgvector:
        initialize-schema: true